# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f991d58f4be5c58dbd1b5d01ec33b0005c4413678feee3c765fdcb773a6a6e7fc8df7969e84a49e62d4a0877d9567249871abe3b641318177bca260fc6d36191

test:
  secret_key_base: 2f7987742a8ba22a564b163783f03b23fc8921f0f606feae03ab1bf2d4905f3b2b05f4fdf6908953c712e27670c8c02aff1316964d5e3d0d803ccf93708aae73

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
